# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-30 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=64)),
                ('blog_content', models.TextField()),
                ('blog_createdat', models.DateTimeField(auto_now_add=True, null=True)),
                ('blog_updatedat', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_ISBN', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=64)),
                ('book_subtitle', models.CharField(blank=True, max_length=64, null=True)),
                ('book_translator', models.CharField(blank=True, max_length=64, null=True)),
                ('book_img', models.CharField(blank=True, max_length=64, null=True)),
                ('book_press', models.CharField(blank=True, max_length=64, null=True)),
                ('book_date', models.CharField(blank=True, max_length=64, null=True)),
                ('book_price', models.CharField(blank=True, max_length=64, null=True)),
                ('book_brief', models.TextField(blank=True, null=True)),
                ('book_catalog', models.TextField(blank=True, null=True)),
                ('book_author', models.CharField(blank=True, max_length=64, null=True)),
                ('book_orititle', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book_tag',
            fields=[
                ('book_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_tag_book_ISBN', models.ForeignKey(db_column='book_tag_book_ISBN', on_delete=django.db.models.deletion.CASCADE, to='tb.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField()),
                ('comment_iscomplained', models.BooleanField(default=False)),
                ('comment_createdat', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment_updatedat', models.DateTimeField(auto_now=True, null=True)),
                ('comment_blog_id', models.ForeignKey(db_column='comment_blog_id', on_delete=django.db.models.deletion.CASCADE, to='tb.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_phone', models.CharField(max_length=64)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_name', models.CharField(blank=True, max_length=64)),
                ('user_gender', models.SmallIntegerField(blank=True, null=True)),
                ('user_password', models.CharField(max_length=64, null=True)),
                ('user_avatar', models.CharField(blank=True, max_length=256, null=True)),
                ('user_createdat', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_updatedat', models.DateTimeField(auto_now=True, null=True)),
                ('user_selfintro', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_blog',
            fields=[
                ('user_blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_blog_like', models.BooleanField(default=False)),
                ('user_blog_focus', models.BooleanField(default=False)),
                ('user_blog_createdat', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_blog_updatedat', models.DateTimeField(auto_now=True, null=True)),
                ('user_blog_blog_id', models.ForeignKey(db_column='user_blog_blog_id', on_delete=django.db.models.deletion.CASCADE, to='tb.Blog')),
                ('user_blog_user_id', models.ForeignKey(db_column='user_blog_user_id', on_delete=django.db.models.deletion.CASCADE, to='tb.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_book',
            fields=[
                ('user_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_book_book_ISBN', models.ForeignKey(db_column='user_book_book_ISBN', on_delete=django.db.models.deletion.CASCADE, to='tb.Book')),
                ('user_book_user_id', models.ForeignKey(db_column='user_book_user_id', on_delete=django.db.models.deletion.CASCADE, to='tb.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_focus',
            fields=[
                ('user_focus_id', models.AutoField(primary_key=True, serialize=False)),
                ('focused_id', models.IntegerField()),
                ('u_id', models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, to='tb.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_tag',
            fields=[
                ('user_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_tag_tag_id', models.ForeignKey(db_column='user_tag_tag_id', on_delete=django.db.models.deletion.CASCADE, to='tb.Tag')),
                ('user_tag_user_id', models.ForeignKey(db_column='user_tag_user_id', on_delete=django.db.models.deletion.CASCADE, to='tb.User')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user_id',
            field=models.ForeignKey(db_column='comment_user_id', on_delete=django.db.models.deletion.CASCADE, to='tb.User'),
        ),
        migrations.AddField(
            model_name='book_tag',
            name='book_tag_tag_id',
            field=models.ForeignKey(db_column='book_tag_tag_id', on_delete=django.db.models.deletion.CASCADE, to='tb.Tag'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_book_ISBN',
            field=models.ForeignKey(db_column='blog_book_ISBN', on_delete=django.db.models.deletion.CASCADE, to='tb.Book'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_user_id',
            field=models.ForeignKey(db_column='blog_user_id', on_delete=django.db.models.deletion.CASCADE, to='tb.User'),
        ),
    ]
