# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-01 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0003_auto_20180430_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_blog',
            name='user_blog_createdat',
            field=models.DateTimeField(default='2018-05-01 11:59:40'),
        ),
    ]
